// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGkRLHJG51AD0JGGKYcCXqb3svAg8qZbw',
    appId: '1:528136352123:web:9c54757307b7589c5ecdde',
    messagingSenderId: '528136352123',
    projectId: 'temmw-inventory',
    authDomain: 'temmw-inventory.firebaseapp.com',
    storageBucket: 'temmw-inventory.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJgA_MfH07O53j6-hnpPpgyqVHOxUMBL0',
    appId: '1:528136352123:android:f5decb2884d486385ecdde',
    messagingSenderId: '528136352123',
    projectId: 'temmw-inventory',
    storageBucket: 'temmw-inventory.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuGXl3OICOIl7HBzadmRLEyN6U03qoR3Q',
    appId: '1:528136352123:ios:130ec7478e2140725ecdde',
    messagingSenderId: '528136352123',
    projectId: 'temmw-inventory',
    storageBucket: 'temmw-inventory.appspot.com',
    iosClientId: '528136352123-66bei2cb1pgle9blf3tnk5hhkntq0gg2.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuGXl3OICOIl7HBzadmRLEyN6U03qoR3Q',
    appId: '1:528136352123:ios:c49967f61deb8e015ecdde',
    messagingSenderId: '528136352123',
    projectId: 'temmw-inventory',
    storageBucket: 'temmw-inventory.appspot.com',
    iosClientId: '528136352123-uu9mnk3u6q6500qg6dsphc95qi0nhcms.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventory.RunnerTests',
  );
}
